services:
  app:
    build: .  
    ports:
      - "8080:8080"
    env_file:
      - ./.env # load environment variables from .env file
    depends_on: # wait for these services to be ready
      - db
      - rabbitmq

  # PostgreSQL database service
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: financial_exchange
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest